version: '3.7'
services:
  flask:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    links:
      - redis
  redis:
    image: redis:alpine
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
    links:
      - flask
