version: '3.7'
services:
  redis:
    image: redis:alpine
    volumes:
      - 'redis:/data/db'
  flask:
    build: ./server
    command: gunicorn -t 60 --worker-class eventlet -w 1 --bind 0.0.0.0:5000 codenames:app
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
    links:
      - flask
    depends_on:
      - flask
    # restart: unless-stopped
volumes:
  redis:
